test

diff --git a/.github/workflows/api-binary-tests.yml b/.github/workflows/api-binary-tests.yml
--- a/.github/workflows/api-binary-tests.yml
+++ b/.github/workflows/api-binary-tests.yml
@@ -74,69 +74,69 @@ jobs:
           path: ./api/dist/
           if-no-files-found: error
  
-  run-test-linux-binary-artifact:
-    name: Run and test linux artifact
-    runs-on: ubuntu-latest
-    needs: build-binary-artifacts  
-    steps:
-      - name: Check out the repo
-        uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 18
+  # run-test-linux-binary-artifact:
+  #   name: Run and test linux artifact
+  #   runs-on: ubuntu-latest
+  #   needs: build-binary-artifacts  
+  #   steps:
+  #     - name: Check out the repo
+  #       uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
 
-      - name: Run mock Keycloak
-        id: idp-run
-        working-directory: test/api/mock-keycloak
-        run: |
-          python3 -m http.server 8080 &
+  #     - name: Run mock Keycloak
+  #       id: idp-run
+  #       working-directory: test/api/mock-keycloak
+  #       run: |
+  #         python3 -m http.server 8080 &
 
       
-      - name: wait 5 seconds
-        run: sleep 5
+  #     - name: wait 5 seconds
+  #       run: sleep 5
 
-      - name: Run MySQL container
-        id: mysql-run
-        run: |
-          docker run -d --name stig-manager-db \
-          -p 3306:3306 \
-          -e MYSQL_ROOT_PASSWORD=rootpw \
-          -e MYSQL_DATABASE=stigman \
-          -e MYSQL_USER=stigman \
-          -e MYSQL_PASSWORD=stigman \
-          mysql:8.0.24
+  #     - name: Run MySQL container
+  #       id: mysql-run
+  #       run: |
+  #         docker run -d --name stig-manager-db \
+  #         -p 3306:3306 \
+  #         -e MYSQL_ROOT_PASSWORD=rootpw \
+  #         -e MYSQL_DATABASE=stigman \
+  #         -e MYSQL_USER=stigman \
+  #         -e MYSQL_PASSWORD=stigman \
+  #         mysql:8.0.24
 
-      - name: wait 10 seconds
-        run: sleep 10
+  #     - name: wait 10 seconds
+  #       run: sleep 10
 
-      - name: Download builds
-        uses: actions/download-artifact@v4
-        with:
-          name: binary-artifacts  
-          path: ./binary-artifacts
+  #     - name: Download builds
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: binary-artifacts  
+  #         path: ./binary-artifacts
 
-      - name: List downloaded files
-        run: ls -l ./binary-artifacts
+  #     - name: List downloaded files
+  #       run: ls -l ./binary-artifacts
 
-      - name: Set execute permissions on binary
-        run: chmod +x ./binary-artifacts/stig-manager-linuxstatic
+  #     - name: Set execute permissions on binary
+  #       run: chmod +x ./binary-artifacts/stig-manager-linuxstatic
       
-      - name: Run linux binary 
-        working-directory: ./
-        run: |
-          echo "Running tests on binary artifacts"
-          ./binary-artifacts/stig-manager-linuxstatic &
+  #     - name: Run linux binary 
+  #       working-directory: ./
+  #       run: |
+  #         echo "Running tests on binary artifacts"
+  #         ./binary-artifacts/stig-manager-linuxstatic &
 
-      - name: Wait for bootstrap
-        run: for i in {1..10}; do [ $i -gt 1 ] && sleep 5; curl --output /dev/null --silent --fail http://localhost:64001/api/op/configuration && s=0 && break || s=$?; printf '.'; done; (exit $s)
+  #     - name: Wait for bootstrap
+  #       run: for i in {1..10}; do [ $i -gt 1 ] && sleep 5; curl --output /dev/null --silent --fail http://localhost:64001/api/op/configuration && s=0 && break || s=$?; printf '.'; done; (exit $s)
           
-      - name: Install test dependencies
-        run: npm ci
-        working-directory: ./test/api/
+  #     - name: Install test dependencies
+  #       run: npm ci
+  #       working-directory: ./test/api/
 
-      - name: Run tests with coverage
-        working-directory: ./test/api/
-        run: npm test
+  #     - name: Run tests with coverage
+  #       working-directory: ./test/api/
+  #       run: npm test
   run-test-windows-binary-artifact:
     name: Run and test Windows artifact (with WSL 2 and Docker)
     runs-on: windows-latest
@@ -190,13 +190,13 @@ jobs:
           echo "Starting Mock Keycloak HTTP server..."
           python3 -m http.server 8080 &
   
-      - name: Start Mock Keycloak HTTP Server in WSL
-        shell: wsl-bash {0}
-        working-directory: test/api/mock-keycloak
-        run: |
-          echo "Starting Mock Keycloak HTTP server again ..."
-          nohup python3 -m http.server 8080 --bind 0.0.0.0 > /dev/null 2>&1 &
-          echo "Mock Keycloak HTTP server started."
+      # - name: Start Mock Keycloak HTTP Server in WSL
+      #   shell: wsl-bash {0}
+      #   working-directory: test/api/mock-keycloak
+      #   run: |
+      #     echo "Starting Mock Keycloak HTTP server again ..."
+      #     nohup python3 -m http.server 8080 --bind 0.0.0.0 > /dev/null 2>&1 &
+      #     echo "Mock Keycloak HTTP server started."
 
       - name: Get WSL2 IP, Forward Ports, and Set Environment Variables
         shell: pwsh
