test

diff --git a/.github/workflows/api-binary-tests.yml b/.github/workflows/api-binary-tests.yml
--- a/.github/workflows/api-binary-tests.yml
+++ b/.github/workflows/api-binary-tests.yml
@@ -48,11 +48,9 @@ jobs:
           script: |
             const repo = await github.rest.repos.get(context.repo)
             return repo.data     
-
       - name: install uglify
         run: |
           sudo npm install -g uglify-js    
-
       - name: run build script
         id: run-the-build-script
         working-directory: ./api
@@ -73,13 +71,13 @@ jobs:
           name: binary-archives
           path: ./api/dist/
           if-no-files-found: error
- 
+
   run-test-linux-binary-artifact:
     name: Run and test linux artifact
     runs-on: ubuntu-latest
     needs: build-binary-artifacts  
     steps:
-    
+     
 
       - name: Check out the repo
         uses: actions/checkout@v4
@@ -132,6 +130,107 @@ jobs:
       - name: Run tests with coverage
         working-directory: ./test/api/
         run: npm test
+  # build-binary-artifacts:
+  #   name: Build binary artifacts
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check out the repo
+  #       uses: actions/checkout@v4
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
+
+  #     - name: Get repository metadata
+  #       id: repo
+  #       uses: actions/github-script@v7
+  #       with:
+  #         script: |
+  #           const repo = await github.rest.repos.get(context.repo)
+  #           return repo.data     
+
+  #     - name: install uglify
+  #       run: |
+  #         sudo npm install -g uglify-js    
+
+  #     - name: run build script
+  #       id: run-the-build-script
+  #       working-directory: ./api
+  #       run: ./build.sh
+   
+  #     - name: Upload builds
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: binary-artifacts
+  #         path: ./api/bin/
+  #         if-no-files-found: error
+
+  #     - name: Upload archives
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: binary-archives
+  #         path: ./api/dist/
+  #         if-no-files-found: error
+ 
+  # run-test-linux-binary-artifact:
+    # name: Run and test linux artifact
+    # runs-on: ubuntu-latest
+    # needs: build-binary-artifacts  
+    # steps:
+    
+
+    #   - name: Check out the repo
+    #     uses: actions/checkout@v4
+    #   - uses: actions/setup-node@v4
+    #     with:
+    #       node-version: 18
+
+    #   - name: Run mock Keycloak
+    #     id: idp-run
+    #     working-directory: test/api/mock-keycloak
+    #     run: |
+    #       python3 -m http.server 8080 &
+    #   - name: Run MySQL container
+    #     id: mysql-run
+    #     run: |
+    #       docker run -d --name stig-manager-db \
+    #       -p 3306:3306 \
+    #       -e MYSQL_ROOT_PASSWORD=rootpw \
+    #       -e MYSQL_DATABASE=stigman \
+    #       -e MYSQL_USER=stigman \
+    #       -e MYSQL_PASSWORD=stigman \
+    #       mysql:8.0.24
+    #   - name: wait 5 seconds
+    #     run: sleep 5
+
+    #   - name: Download builds
+    #     uses: actions/download-artifact@v4
+    #     with:
+    #       name: binary-artifacts  
+    #       path: ./binary-artifacts
+
+    #   - name: List downloaded files
+    #     run: ls -l ./binary-artifacts
+
+    #   - name: Set execute permissions on binary
+    #     run: chmod +x ./binary-artifacts/stig-manager-linuxstatic
+      
+    #   - name: Run linux binary 
+    #     working-directory: ./
+    #     run: |
+    #       echo "Running tests on binary artifacts"
+    #       ./binary-artifacts/stig-manager-linuxstatic &
+    #   - name: Wait for bootstrap
+    #     run: for i in {1..10}; do [ $i -gt 1 ] && sleep 5; curl --output /dev/null --silent --fail http://localhost:64001/api/op/configuration && s=0 && break || s=$?; printf '.'; done; (exit $s)
+          
+    #   - name: Install test dependencies
+    #     run: npm ci
+    #     working-directory: ./test/api/
+
+    #   - name: Run tests with coverage
+    #     working-directory: ./test/api/
+    #     run: npm test
   # run-test-linux-binary-artifact:
   #   name: Run and test linux artifact
   #   runs-on: ubuntu-latest
